# -*- coding: utf-8 -*-
"""student_performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NI8Zd_CEfPl2GavQE4FpuWtZp8MDnM8U
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# %matplotlib inline

plt.style.use("ggplot")

df = pd.read_csv("sample_data/student_performance_dataset.csv")
df.head()

print("Shape:", df.shape)

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

df.dtypes

plt.figure(figsize=(8,5))
sns.histplot(df["final_exam_score"], bins=20, kde=True)

plt.title("Distribution of Final Exam Scores")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="gender")

plt.title("Gender Distribution")
plt.show()

plt.figure(figsize=(6,4))
sns.countplot(data=df, x="performance_category")
plt.title("Performance Categories")
plt.show

plt.figure(figsize=(8,5))
sns.scatterplot(data=df, x="study_hours_per_day", y="final_exam_score", hue="performance_category")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(data=df, x="attendance_percentage", y="final_exam_score")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["social_media_hours"],bins=20, kde=True)
plt.title("Distribution of Daily Social Media Usage")
plt.xlabel("Hours per day")
plt.ylabel("Number of Students")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(data=df,x="social_media_hours", y="final_exam_score", hue="performance_category")
plt.title("Social Media Usage Vs Final Exam Score")
plt.show()

plt.figure(figsize=(7,5))
sns.boxplot(data=df, x="performance_category", y="social_media_hours")
plt.title("Social Media Usage Across Performance Categories")
plt.show()

df = pd.read_csv("sample_data/student_performance_dataset.csv")

df["doomscrolling_before_sleep"] = df["doomscrolling_before_sleep"].replace({
    0: "No",
    1: "Yes"
})

print(df["doomscrolling_before_sleep"].value_counts(dropna=False))

plt.figure(figsize=(6, 4))

ax = sns.countplot(
    data=df,
    x="doomscrolling_before_sleep",
    order=["No", "Yes"],
    color="skyblue"
)

plt.title("Students Who Doomscroll Before Sleeping")
plt.xlabel("Doomscrolling Before Sleep")
plt.ylabel("Number of Students")

for container in ax.containers:
    ax.bar_label(container)

plt.tight_layout()
plt.show()

label=LabelEncoder()
for col in df.select_dtypes(include="object", ).columns:
    df[col]=label.fit_transform(df[col])

x=df.drop("performance_category", axis=1)
y=df["performance_category"]

X_train, X_test, y_train, y_test= train_test_split(x,y,test_size=0.2, random_state=42)

model=RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

predictions=model.predict(X_test)

accuracy = accuracy_score(y_test, predictions)
print("Accuracy: ", accuracy)

print(classification_report(y_test,predictions))

cm =confusion_matrix(y_test,predictions)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

importance = pd.DataFrame({
    "Feature": x.columns,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(10)

accuracy = accuracy_score(y_test, predictions)
print("Accuracy: ", accuracy)

plt.figure(figsize=(10,6))
sns.barplot(data=importance.head(10),x="Importance", y="Feature")
plt.title("Top 10 most important features")
plt.show()

sns.boxplot(x="gender", y="performance_category", data=df)

df.columns

df['ai_dependency']=(
    df['ai_tool_usage_hours']/(df['study_hours_per_day'] + 1)
)

plt.figure(figsize=(8,5))

sns.scatterplot(
    x="study_hours_per_day",
    y="final_exam_score",
    hue="performance_category",
    data=df
)

plt.title("Study Hours vs Final Exam Score")
plt.show()

df.columns

from sklearn.tree import DecisionTreeClassifier


model2=DecisionTreeClassifier(random_state=42)
model2.fit(X_train, y_train)

predictions_decision_tree=model2.predict(X_test)

accuracy_decision_tree = accuracy_score(y_test, predictions_decision_tree)
print("Accuracy: ", accuracy_decision_tree)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x_train=scaler.fit_transform(X_train)
x_test=scaler.transform(X_test)

df = df.dropna()

from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="mean")

x_train = imputer.fit_transform(x_train)
x_test = imputer.transform(x_test)

model3 = SVC(random_state=42)
model3.fit(x_train, y_train)

from sklearn.neighbors import KNeighborsClassifier

model4 = KNeighborsClassifier()
model4.fit(x_train, y_train)
y_pred = model4.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

import mlflow

mlflow.set_experiment("My Application")
mlflow.set_tracking_uri("http://localhost:5000")